# Data Preprocessing
The Data Preprocessing is a technique to transform the raw data into a cleaned data before feeding it to the algorithms. This gives a significant amount of improvements to the model and can be evaluated oon the metrics and the improvement is also dependent on the dataset on which preprocessing is been applied.

There are several techniques used for the data preprocessing:
# 1. Rescaling :
When a data has different features with different scale then this could lead to significant amount of error. Many times the applied algorithms can be benefitted with the rescaled data. Rescaling the data allows datasset to be on same scale and be in between defined upper and lower bounds. This is useful for the weighted inputs used mainly in the regression and algorithms like k nearest neighbour that uses distance measures for evaluation.


In [ ]:
# Edit before running
# Python code to Rescale data (between 0 and 1) 

import pandas 
import scipy 
import numpy 
from sklearn.preprocessing import MinMaxScaler 

dataframe = pandas.read_csv("enter csv file of dataset") 
array = dataframe.values 
  
# separate array into input and output components 
X =  # input features
Y = # target feature in case of regression
scaler = MinMaxScaler(feature_range=(0, 1)) 
rescaledX = scaler.fit_transform(X) 
  
# summarize transformed data 
numpy.set_printoptions(precision=3) 
print(rescaledX)

Output be like the cell below: 

# Sample output
[[ 0.353  0.744  0.59   0.354  0.0    0.501  0.234  0.483]
 [ 0.059  0.427  0.541  0.293  0.0    0.396  0.117  0.167]
 [ 0.471  0.92   0.525  0.     0.0    0.347  0.254  0.183]]

# 2. Standardize Data:
• Standardization is a useful technique to transform attributes with a Gaussian distribution and differing means and standard deviations to a standard Gaussian distribution with a mean of 0 and a standard deviation of 1.

In [ ]:
# Edit before running
# Python code to Standardize data (0 mean, 1 stdev) 

from sklearn.preprocessing import StandardScaler 
import pandas 
import scipy 
import numpy  

dataframe = pandas.read_csv("enter csv file of dataset") 
array = dataframe.values 
  
# separate array into input and output components 
X =  # input features
Y = # target feature in case of regression
scaler = StandardScaler().fit(X) 
rescaledX = scaler.transform(X) 
  
# summarize transformed data 
numpy.set_printoptions(precision=3) 
print(rescaledX)

Output be like:

[[1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106]
 [-0.845 -0.998 -0.161  0.155  0.123 -0.494 -0.921 -1.042]
 [-1.142  0.504 -1.505  0.907  0.766  1.41 ]]

# 3. Imputation:
This technique is used to deal with the missing values.Imputation fills in the missing value with some number(it is complicated). The imputed value won't be exactly right in most cases, but it usually gives more accurate models than dropping the column entirely.


In [ ]:
# Imputation template
# edit required fields
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('DataFile.csv')
X = 'input feature column'
y = target feature colums

# Taking care of missing data
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3]

# 4. Hot encoding:
This is to deal with the categorical data (data columns with the datatype = object) as many machine learning algorithms do not work efficiently on catagorical data. One hot encoding creates new (binary) columns, indicating the presence of each possible value from the original data. THis is helpful  unless categorical data takes on a large number of values.

In [ ]:
# Hot encoding  template
# edit required fields
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
# Importing the dataset
dataset = pd.read_csv('DataFile.csv')
X = 'input feature column'
y = target feature colums


labelencoder_X = LabelEncoder()
X = labelencoder_X.fit_transform(X[:, 0])
onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray()

# Encoding the Dependent Variable
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
print(X,y)